language: cpp
compiler:
  - gcc
before_install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install rpm cmake
script:
    - mkdir build_temp
    - cd build_temp
    - cmake ../
    - make
    - make package
notifications:
    channels:
      - "irc.flightgear.org#fgx"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change